(function(){
  "use strict"
  const root=document.getElementById("root"),toast=document.getElementById("toast")
  const state={token:localStorage.getItem("shuzhi-web-token")||"",user:null,view:"dashboard",files:[]}
  const nav={admin:[["dashboard","总览"],["students","学生与名单"],["counselors","辅导员与班级"],["content","内容审核"],["tasks","测评任务"],["logs","审计日志"]],counselor:[["dashboard","工作台"],["classes","我的班级"],["risks","风险跟进"],["articles","文章发布"]]}
  const titles={dashboard:["工作总览","今天也一起把重要的事情做稳。"],students:["学生与名单","上传、预检、确认，三步完成学生账号建立。"],counselors:["辅导员与班级","由管理员统一建号，并按学期分配负责班级。"],content:["内容审核","审核辅导员提交的图文与视频内容。"],tasks:["测评任务","查看全校测评任务与执行状态。"],logs:["审计日志","关键管理操作留痕可追溯。"],classes:["我的班级","只显示当前学期已授权班级。"],risks:["风险跟进","仅用于学生支持，不作为诊断或处分依据。"],articles:["文章发布","支持从手机或电脑选择本地图片、视频。"]}

  function h(v){return String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
  function notice(message,error){toast.textContent=message;toast.className="toast show"+(error?" error":"");clearTimeout(notice.timer);notice.timer=setTimeout(()=>toast.className="toast",3000)}
  async function api(path,options={}){const headers=Object.assign({},options.headers||{});if(state.token)headers.Authorization="Bearer "+state.token;if(options.body&&!(options.body instanceof Blob)&&!(options.body instanceof ArrayBuffer)&&!headers["Content-Type"])headers["Content-Type"]="application/json";const response=await fetch(path,Object.assign({},options,{headers}));const text=await response.text();let body={};try{body=text?JSON.parse(text):{}}catch(_){body={}}if(!response.ok){if(response.status===401){logout(false)}throw new Error(body.error&&body.error.message||"请求失败")};return body.data}
  function roleName(role){return role==="admin"?"管理员":"辅导员"}
  function badge(value){const cls=/已发布|已导入|已完成|正常/.test(value)?"ok":/紧急|较高|校验失败|已退回/.test(value)?"alert":"warn";return `<span class="badge ${cls}">${h(value)}</span>`}
  function mediaHtml(media){if(!media||!media.length)return"";return `<div class="media-grid">${media.map(m=>m.kind==="video"?`<video controls preload="metadata" src="${h(m.url)}"></video>`:`<img loading="lazy" src="${h(m.url)}" alt="${h(m.name)}">`).join("")}</div>`}

  async function restore(){if(!state.token)return bindLogin();try{state.user=await api("/api/v1/account");if(!["admin","counselor"].includes(state.user.role))throw new Error("当前账号不能登录管理端");state.user.mustChangePassword?renderForcedPassword():renderShell()}catch(error){logout(false);notice(error.message,true)}}
  function bindLogin(){const form=document.getElementById("login-form");if(!form)return;form.addEventListener("submit",async event=>{event.preventDefault();const button=form.querySelector("button");button.disabled=true;button.textContent="正在登录…";try{const data=await api("/api/v1/auth/login",{method:"POST",body:JSON.stringify({role:document.getElementById("login-role").value,accountId:document.getElementById("login-account").value,password:document.getElementById("login-password").value})});state.token=data.token;state.user=data.user;localStorage.setItem("shuzhi-web-token",state.token);state.user.mustChangePassword?renderForcedPassword():renderShell()}catch(error){notice(error.message,true)}finally{button.disabled=false;button.textContent="登录管理端"}})}
  function renderForcedPassword(){root.innerHTML=`<main class="login-page"><section class="login-card"><div class="login-brand"><span class="brand-mark">心</span><div><h1>首次登录需要改密</h1><p>${h(state.user.displayName||state.user.accountId)}，当前使用的是临时密码。</p></div></div><form id="forced-password-form"><label>当前临时密码<input id="forced-current" type="password" autocomplete="current-password" required></label><label>新密码<input id="forced-new" type="password" minlength="8" maxlength="64" autocomplete="new-password" required placeholder="8至64位"></label><label>再次输入新密码<input id="forced-confirm" type="password" minlength="8" maxlength="64" autocomplete="new-password" required></label><button class="button primary wide" type="submit">修改密码并重新登录</button><button class="button secondary wide" id="forced-logout" type="button">退出登录</button></form></section></main>`;document.getElementById("forced-logout").onclick=()=>logout();document.getElementById("forced-password-form").onsubmit=async event=>{event.preventDefault();const current=document.getElementById("forced-current").value,next=document.getElementById("forced-new").value,confirmValue=document.getElementById("forced-confirm").value;if(next!==confirmValue)return notice("两次输入的新密码不一致",true);const button=event.target.querySelector("button[type=submit]");button.disabled=true;try{await api("/api/v1/account/password",{method:"POST",body:JSON.stringify({currentPassword:current,newPassword:next})});localStorage.removeItem("shuzhi-web-token");alert("密码修改成功，请使用新密码重新登录。");location.reload()}catch(error){notice(error.message,true);button.disabled=false}}}
  async function logout(callApi=true){if(callApi&&state.token)try{await api("/api/v1/auth/logout",{method:"POST"})}catch(_){}localStorage.removeItem("shuzhi-web-token");location.reload()}
  function renderShell(){const menu=nav[state.user.role];const title=titles[state.view]||titles.dashboard;root.innerHTML=`<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="side-brand">数智心港湾<small>CAMPUS CLOUD</small></div><nav class="nav">${menu.map(([key,label])=>`<button data-view="${key}" class="${state.view===key?"active":""}">${label}</button>`).join("")}</nav><div class="side-user"><strong>${h(state.user.displayName||state.user.accountId)}</strong><span>${roleName(state.user.role)} · ${h(state.user.accountId)}</span><button class="logout" id="logout">退出登录</button></div></aside><section class="workspace"><header class="topbar"><div><button class="mobile-menu" id="menu">菜单</button><h1>${title[0]}</h1><p>${title[1]}</p></div><span class="badge ok">校园云已连接</span></header><div id="view"><div class="empty"><span class="spinner"></span><p>正在读取数据…</p></div></div></section></div>`;document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;renderShell()});document.getElementById("logout").onclick=()=>logout();document.getElementById("menu").onclick=()=>document.getElementById("sidebar").classList.toggle("open");loadView().catch(e=>{document.getElementById("view").innerHTML=`<div class="card empty">${h(e.message)}</div>`;notice(e.message,true)})}
  async function loadView(){if(state.user.role==="admin"){if(state.view==="dashboard")return adminDashboard();if(state.view==="students")return adminStudents();if(state.view==="counselors")return adminCounselors();if(state.view==="content")return adminContent();if(state.view==="tasks")return adminTasks();if(state.view==="logs")return adminLogs()}else{if(state.view==="dashboard")return counselorDashboard();if(state.view==="classes")return counselorClasses();if(state.view==="risks")return counselorRisks();if(state.view==="articles")return counselorArticles()}}
  const view=()=>document.getElementById("view")

  async function adminDashboard(){const [students,counselors,classes,content]=await Promise.all([api("/api/v1/admin/students"),api("/api/v1/admin/counselors"),api("/api/v1/admin/classes"),api("/api/v1/admin/content-items")]);const pending=content.filter(x=>x.status==="待审核"),unassigned=classes.filter(x=>x.active&&!x.counselor);view().innerHTML=`<div class="grid stats"><div class="stat"><small>学生账号</small><b>${students.length}</b></div><div class="stat"><small>辅导员账号</small><b>${counselors.filter(x=>x.active).length}</b></div><div class="stat"><small>未分配班级</small><b>${unassigned.length}</b></div><div class="stat"><small>待审内容</small><b>${pending.length}</b></div></div><div class="grid two" style="margin-top:18px"><section class="card"><h2>班级分配提醒</h2>${unassigned.slice(0,8).map(x=>`<p><b>${h(x.name)}</b><br><span class="hint">${x.studentCount}名学生 · 当前学期未分配辅导员</span></p>`).join("")||'<div class="empty">当前学期所有班级均已分配</div>'}</section><section class="card"><h2>待审核内容</h2>${pending.slice(0,5).map(x=>`<p><b>${h(x.title)}</b><br><span class="hint">${h(x.authorName)} · ${h(x.createdAt)}</span></p>`).join("")||'<div class="empty">暂无待审内容</div>'}</section></div>`}
  async function adminStudents(){const [students,batches]=await Promise.all([api("/api/v1/admin/students"),api("/api/v1/admin/import-batches")]);view().innerHTML=`<section class="card"><div class="section-title"><div><h2>上传学生名单</h2><p class="hint">固定两列：班级、学号。支持 Excel .xlsx、TXT 和 CSV，单次最多500人。新账号初始密码为学号后4位。</p></div></div><div class="dropzone"><input id="roster-file" type="file" accept=".xlsx,.txt,.csv"><p class="hint">Excel 请使用 .xlsx 格式；TXT 可使用逗号或 Tab 分隔。</p></div><div id="import-preview"></div></section><section class="card" style="margin-top:18px"><h2>学生账号 <span class="badge">${students.length}</span></h2><div class="table-wrap"><table class="table"><thead><tr><th>学号</th><th>班级</th><th>姓名</th><th>账号状态</th><th>初始化</th><th>操作</th></tr></thead><tbody>${students.map(s=>`<tr><td>${h(s.studentId)}</td><td>${h(s.className||s.classId)}</td><td>${h(s.studentName)||'<span class="muted">待学生填写</span>'}</td><td>${badge(s.active?"启用":"停用")}</td><td>${s.mustChangePassword?badge("待改密码"):badge("已完成")}</td><td><button class="button secondary reset-password" data-id="${h(s.studentId)}">重置密码</button></td></tr>`).join("")}</tbody></table></div></section><section class="card" style="margin-top:18px"><h2>导入批次</h2>${batches.length?`<div class="table-wrap"><table class="table"><thead><tr><th>文件</th><th>状态</th><th>总行数</th><th>新增</th><th>更新</th><th>时间</th></tr></thead><tbody>${batches.map(b=>`<tr><td>${h(b.fileName)}</td><td>${badge(b.status)}</td><td>${b.totalRows}</td><td>${b.createCount}</td><td>${b.updateCount}</td><td>${h(b.createdAt)}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">暂无导入批次</div>'}</section>`;document.getElementById("roster-file").onchange=e=>previewRoster(e.target.files[0]);document.querySelectorAll(".reset-password").forEach(b=>b.onclick=async()=>{if(!confirm("确认将该学生密码重置为学号后4位？"))return;try{await api(`/api/v1/admin/students/${encodeURIComponent(b.dataset.id)}/reset-password`,{method:"POST",body:"{}"});notice("密码已重置，学生下次登录必须修改") }catch(e){notice(e.message,true)}})}
  async function previewRoster(file){if(!file)return;const box=document.getElementById("import-preview");box.innerHTML='<div class="empty"><span class="spinner"></span><p>正在解析并预检…</p></div>';try{const csvText=await rosterToCsv(file);const data=await api("/api/v1/admin/import-batches/preview",{method:"POST",body:JSON.stringify({clientBatchId:"web:"+crypto.randomUUID(),fileName:file.name.replace(/\.[^.]+$/,"")+".csv",format:"student-roster",csvText})});box.innerHTML=`<div class="batch-summary"><span>总数 <b>${data.totalRows}</b></span><span>新增 <b>${data.createCount}</b></span><span>更新 <b>${data.updateCount}</b></span><span>不变 <b>${data.unchangedCount}</b></span></div>${data.errors&&data.errors.length?`<div class="error-list">${data.errors.map(e=>`<div>第${e.rowNumber}行 · ${h(e.field)}：${h(e.message)}</div>`).join("")}</div>`:`<button id="confirm-import" class="button primary">确认导入这 ${data.totalRows} 名学生</button>`}`;const confirmButton=document.getElementById("confirm-import");if(confirmButton)confirmButton.onclick=async()=>{confirmButton.disabled=true;try{await api(`/api/v1/admin/import-batches/${data.id}/confirm`,{method:"POST",body:"{}"});notice("学生名单已导入");adminStudents()}catch(e){notice(e.message,true);confirmButton.disabled=false}}}catch(e){box.innerHTML=`<div class="error-list">${h(e.message)}</div>`}}

  async function adminCounselors(){
    const [counselors,semesters]=await Promise.all([api("/api/v1/admin/counselors"),api("/api/v1/admin/semesters")])
    const current=semesters.find(x=>x.status==="当前学期")||semesters[0]
    if(!state.counselorSemester&&current)state.counselorSemester=current.id
    const semesterId=state.counselorSemester||""
    const classes=await api("/api/v1/admin/classes?semesterId="+encodeURIComponent(semesterId))
    const activeCounselors=counselors.filter(x=>x.active)
    view().innerHTML=`<div class="grid two"><section class="card"><h2>创建辅导员账号</h2><p class="hint">辅导员不能自行注册。临时密码统一为 <b>123456</b>，首次登录强制修改。</p><form id="counselor-create"><div class="form-row"><label>工号<input id="counselor-staff" maxlength="32" required placeholder="例如 T002"></label><label>姓名<input id="counselor-name" maxlength="50" required placeholder="辅导员姓名"></label></div><button class="button primary" type="submit">创建账号</button></form></section><section class="card"><h2>分配规则</h2><p>同一学期、同一班级只保留一名当前负责辅导员。</p><p class="hint">更换辅导员时，系统会结束原分配并保留审计记录；停用账号会立即让其现有会话失效。</p></section></div><section class="card" style="margin-top:18px"><h2>辅导员账号 <span class="badge">${counselors.length}</span></h2>${counselors.length?`<div class="table-wrap"><table class="table"><thead><tr><th>工号</th><th>姓名</th><th>状态</th><th>密码状态</th><th>有效分配</th><th>操作</th></tr></thead><tbody>${counselors.map(c=>`<tr><td>${h(c.staffId)}</td><td>${h(c.displayName)}</td><td>${badge(c.active?"启用":"停用")}</td><td>${c.mustChangePassword?badge("待首次改密"):badge("已改密")}</td><td>${c.activeClassCount}</td><td><button class="button secondary counselor-reset" data-staff="${h(c.staffId)}">重置为123456</button> <button class="button ${c.active?"danger":"secondary"} counselor-status" data-staff="${h(c.staffId)}" data-active="${c.active?"0":"1"}">${c.active?"停用":"启用"}</button></td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">还没有辅导员账号</div>'}</section><section class="card" style="margin-top:18px"><div class="section-title"><div><h2>按学期分配班级</h2><p class="hint">仅已启用的辅导员可被分配。</p></div><label>学期<select id="assignment-semester">${semesters.map(s=>`<option value="${h(s.id)}" ${s.id===semesterId?"selected":""}>${h(s.name)} · ${h(s.status)}</option>`).join("")}</select></label></div><div class="table-wrap"><table class="table"><thead><tr><th>班级</th><th>学生数</th><th>当前负责人</th><th>选择辅导员</th><th>操作</th></tr></thead><tbody>${classes.filter(c=>c.active).map(c=>`<tr><td><b>${h(c.name)}</b><br><span class="hint">${h(c.major)}</span></td><td>${c.studentCount}</td><td>${c.counselor?`${h(c.counselor.displayName)}<br><span class="hint">${h(c.counselor.staffId)}</span>`:'<span class="badge warn">未分配</span>'}</td><td><select class="assignment-select" data-class="${h(c.id)}"><option value="">请选择</option>${activeCounselors.map(x=>`<option value="${h(x.staffId)}" ${c.counselor&&c.counselor.staffId===x.staffId?"selected":""}>${h(x.displayName)}（${h(x.staffId)}）</option>`).join("")}</select></td><td><button class="button primary assignment-save" data-class="${h(c.id)}">保存分配</button>${c.counselor?` <button class="button danger assignment-revoke" data-class="${h(c.id)}" data-staff="${h(c.counselor.staffId)}">撤销</button>`:""}</td></tr>`).join("")}</tbody></table></div></section>`
    document.getElementById("counselor-create").onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector("button");button.disabled=true;try{await api("/api/v1/admin/counselors",{method:"POST",body:JSON.stringify({staffId:document.getElementById("counselor-staff").value,displayName:document.getElementById("counselor-name").value})});notice("辅导员账号已创建，临时密码为123456");adminCounselors()}catch(e){notice(e.message,true);button.disabled=false}}
    const semesterSelect=document.getElementById("assignment-semester");if(semesterSelect)semesterSelect.onchange=()=>{state.counselorSemester=semesterSelect.value;adminCounselors()}
    document.querySelectorAll(".counselor-reset").forEach(b=>b.onclick=async()=>{if(!confirm(`确认将 ${b.dataset.staff} 的密码重置为123456？`))return;try{await api(`/api/v1/admin/counselors/${encodeURIComponent(b.dataset.staff)}/reset-password`,{method:"POST",body:"{}"});notice("密码已重置，该账号下次登录必须改密");adminCounselors()}catch(e){notice(e.message,true)}})
    document.querySelectorAll(".counselor-status").forEach(b=>b.onclick=async()=>{const active=b.dataset.active==="1";if(!confirm(`确认${active?"启用":"停用"} ${b.dataset.staff} ？`))return;try{await api(`/api/v1/admin/counselors/${encodeURIComponent(b.dataset.staff)}/status`,{method:"PATCH",body:JSON.stringify({active})});notice(active?"账号已启用":"账号已停用");adminCounselors()}catch(e){notice(e.message,true)}})
    document.querySelectorAll(".assignment-save").forEach(b=>b.onclick=async()=>{const select=Array.from(document.querySelectorAll(".assignment-select")).find(x=>x.dataset.class===b.dataset.class),staffId=select&&select.value;if(!staffId)return notice("请先选择辅导员",true);try{await api("/api/v1/admin/counselor-assignments",{method:"POST",body:JSON.stringify({staffId,classId:b.dataset.class,semesterId})});notice("班级负责辅导员已更新");adminCounselors()}catch(e){notice(e.message,true)}})
    document.querySelectorAll(".assignment-revoke").forEach(b=>b.onclick=async()=>{if(!confirm("确认撤销该班级分配？"))return;try{await api("/api/v1/admin/counselor-assignments",{method:"PATCH",body:JSON.stringify({staffId:b.dataset.staff,classId:b.dataset.class,semesterId})});notice("班级分配已撤销");adminCounselors()}catch(e){notice(e.message,true)}})
  }

  async function adminContent(){const items=await api("/api/v1/admin/content-items");view().innerHTML=items.length?`<div class="grid two">${items.map(articleCard).join("")}</div>`:'<div class="card empty">暂无内容</div>';document.querySelectorAll(".approve").forEach(b=>b.onclick=()=>reviewContent(b.dataset.id,"已发布",""));document.querySelectorAll(".reject").forEach(b=>b.onclick=()=>{const reason=prompt("请填写退回原因");if(reason)reviewContent(b.dataset.id,"已退回",reason)})}
  function articleCard(x){return `<article class="card content-card"><div class="content-meta">${badge(x.status)}<span class="badge">${x.type==="civics"?"思政育人":"心理科普"}</span><span class="badge">${h(x.category)}</span></div><h2>${h(x.title)}</h2><p class="hint">${h(x.authorName)} · ${h(x.createdAt)}</p><p>${h(x.summary)}</p>${mediaHtml(x.media)}<details><summary>查看正文</summary><div class="article-body">${h(x.content)}</div></details>${x.reviewNote?`<p class="error-list">审核意见：${h(x.reviewNote)}</p>`:""}${x.status==="待审核"?`<div class="content-actions"><button class="button primary approve" data-id="${x.id}">通过并发布</button><button class="button danger reject" data-id="${x.id}">退回</button></div>`:""}</article>`}
  async function reviewContent(id,status,reviewNote){try{await api(`/api/v1/admin/content-items/${id}/review`,{method:"PATCH",body:JSON.stringify({status,reviewNote})});notice(status==="已发布"?"内容已发布":"内容已退回");adminContent()}catch(e){notice(e.message,true)}}
  async function adminTasks(){const tasks=await api("/api/v1/admin/assessment-tasks");view().innerHTML=`<section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>任务</th><th>学期</th><th>范围</th><th>截止日期</th><th>状态</th></tr></thead><tbody>${tasks.map(t=>`<tr><td>${h(t.title)}</td><td>${h(t.semesterName)}</td><td>${h(t.targetClassName)}</td><td>${h(t.deadline)}</td><td>${badge(t.status)}</td></tr>`).join("")}</tbody></table></div></section>`}
  async function adminLogs(){const logs=await api("/api/v1/admin/audit-logs?limit=150");view().innerHTML=`<section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>时间</th><th>操作人</th><th>行为</th><th>对象</th></tr></thead><tbody>${logs.map(x=>`<tr><td>${h(x.createdAt)}</td><td>${h(x.actorName)}<br><span class="hint">${h(x.actorAccountId)}</span></td><td>${h(x.action)}</td><td>${h(x.targetType)} ${h(x.targetId)}</td></tr>`).join("")}</tbody></table></div></section>`}

  async function counselorDashboard(){const [classes,risks,content]=await Promise.all([api("/api/v1/counselor/classes"),api("/api/v1/counselor/risk-events"),api("/api/v1/counselor/content-items/mine")]);view().innerHTML=`<div class="grid stats"><div class="stat"><small>授权班级</small><b>${classes.length}</b></div><div class="stat"><small>学生总数</small><b>${classes.reduce((n,x)=>n+x.total,0)}</b></div><div class="stat"><small>待跟进事件</small><b>${risks.filter(x=>x.status!=="已关闭").length}</b></div><div class="stat"><small>我的文章</small><b>${content.length}</b></div></div><div class="grid two" style="margin-top:18px"><section class="card"><h2>班级概览</h2>${classes.map(c=>`<p><b>${h(c.name)}</b> <span class="hint">${c.completed}/${c.total}已完成 · ${c.highRisk}人需重点关注</span></p>`).join("")||'<div class="empty">尚未分配班级</div>'}</section><section class="card"><h2>最近风险事件</h2>${risks.slice(0,5).map(r=>`<p>${badge(r.level)} <b>${h(r.studentName||r.studentId)}</b><br><span class="hint">${h(r.className)} · ${h(r.status)}</span></p>`).join("")||'<div class="empty">暂无风险事件</div>'}</section></div>`}
  async function counselorClasses(){const classes=await api("/api/v1/counselor/classes");view().innerHTML=`<div class="grid class-grid">${classes.map(c=>`<article class="card class-card" data-class="${h(c.id)}"><span class="badge">${c.total}名学生</span><h2>${h(c.name)}</h2><p class="hint">已完成 ${c.completed}人 · 重点关注 ${c.highRisk}人</p><div class="progress"><span style="width:${c.rate}%"></span></div></article>`).join("")||'<div class="card empty">尚未分配班级</div>'}</div><div id="class-detail" class="detail-panel"></div>`;document.querySelectorAll(".class-card").forEach(c=>c.onclick=()=>loadClass(c.dataset.class))}
  async function loadClass(id){const box=document.getElementById("class-detail");box.innerHTML='<div class="card empty"><span class="spinner"></span></div>';try{const d=await api(`/api/v1/counselor/classes/${encodeURIComponent(id)}/summary`);box.innerHTML=`<section class="card"><h2>${h(d.name)} · 学生概况</h2><div class="batch-summary"><span>总人数 <b>${d.summary.total}</b></span><span>完成率 <b>${d.summary.completionRate}%</b></span><span>平均健康指数 <b>${d.summary.averageWellbeingIndex}</b></span></div><div class="table-wrap"><table class="table"><thead><tr><th>学号</th><th>姓名</th><th>完成状态</th><th>最新结果</th><th>时间</th></tr></thead><tbody>${d.students.map(s=>`<tr><td>${h(s.studentId)}</td><td>${h(s.studentName)||"未填写"}</td><td>${badge(s.completion)}</td><td>${badge(s.riskLevel)}</td><td>${h(s.latestAt)}</td></tr>`).join("")}</tbody></table></div></section>`}catch(e){box.innerHTML=`<div class="error-list">${h(e.message)}</div>`}}
  async function counselorRisks(){const risks=await api("/api/v1/counselor/risk-events");view().innerHTML=risks.length?`<div class="grid two">${risks.map(r=>`<article class="card"><div class="content-meta">${badge(r.level)}${badge(r.status)}</div><h2>${h(r.studentName||r.studentId)}</h2><p class="hint">${h(r.className)} · ${h(r.source)}</p><p>${h(r.summary)}</p><label>跟进状态<select class="risk-status"><option ${r.status==="待确认"?"selected":""}>待确认</option><option ${r.status==="跟进中"?"selected":""}>跟进中</option><option ${r.status==="已关闭"?"selected":""}>已关闭</option></select></label><label>跟进记录<textarea class="risk-note">${h(r.followupNote)}</textarea></label><button class="button primary save-risk" data-id="${r.id}">保存跟进</button></article>`).join("")}</div>`:'<div class="card empty">暂无风险事件</div>';document.querySelectorAll(".save-risk").forEach(b=>b.onclick=async()=>{const card=b.closest("article");try{await api(`/api/v1/counselor/risk-events/${b.dataset.id}`,{method:"PATCH",body:JSON.stringify({status:card.querySelector(".risk-status").value,followupNote:card.querySelector(".risk-note").value})});notice("跟进记录已保存")}catch(e){notice(e.message,true)}})}
  async function counselorArticles(){const items=await api("/api/v1/counselor/content-items/mine");view().innerHTML=`<div class="grid two"><section class="card"><h2>创建新文章</h2><form id="article-form"><div class="form-row"><label>内容类型<select id="article-type"><option value="psychoeducation">心理科普</option><option value="civics">思政育人</option></select></label><label>分类<input id="article-category" maxlength="80" placeholder="例如：压力管理"></label></div><label>标题<input id="article-title" maxlength="160" required></label><label>摘要<textarea id="article-summary" maxlength="500" style="min-height:80px"></textarea></label><label>正文<textarea id="article-content" maxlength="20000" required></textarea></label><label>本地图片 / 视频<input id="article-media" type="file" accept="image/jpeg,image/png,image/gif,image/webp,video/mp4,video/webm,video/quicktime" multiple></label><p class="hint">每篇最多9个文件；单文件最大100MB。视频推荐 MP4，兼容手机和电脑播放。</p><div id="file-preview" class="preview-files"></div><button class="button primary wide" type="submit">上传并提交审核</button></form></section><section><h2>我的文章</h2><div class="grid">${items.map(articleCard).join("")||'<div class="card empty">还没有提交过文章</div>'}</div></section></div>`;state.files=[];document.getElementById("article-media").onchange=e=>{state.files=Array.from(e.target.files).slice(0,9);document.getElementById("file-preview").innerHTML=state.files.map(f=>`<div class="preview-file"><span>${h(f.name)}</span><span>${formatBytes(f.size)}</span></div>`).join("")};document.getElementById("article-form").onsubmit=submitArticle}
  async function submitArticle(event){event.preventDefault();const button=event.target.querySelector("button[type=submit]");button.disabled=true;try{const mediaIds=[];for(let i=0;i<state.files.length;i++){button.textContent=`正在上传 ${i+1}/${state.files.length}…`;const f=state.files[i];const media=await api("/api/v1/counselor/media",{method:"POST",headers:{"Content-Type":f.type,"X-File-Name":encodeURIComponent(f.name)},body:f});mediaIds.push(media.id)}button.textContent="正在提交审核…";await api("/api/v1/counselor/content-items",{method:"POST",body:JSON.stringify({type:document.getElementById("article-type").value,category:document.getElementById("article-category").value,title:document.getElementById("article-title").value,summary:document.getElementById("article-summary").value,content:document.getElementById("article-content").value,mediaIds})});notice("文章已提交，等待管理员审核");counselorArticles()}catch(e){notice(e.message,true)}finally{button.disabled=false;button.textContent="上传并提交审核"}}
  function formatBytes(n){return n<1024*1024?Math.ceil(n/1024)+"KB":(n/1024/1024).toFixed(1)+"MB"}

  async function rosterToCsv(file){const ext=(file.name.split(".").pop()||"").toLowerCase();if(ext==="xlsx")return xlsxToCsv(await file.arrayBuffer());if(ext==="txt"||ext==="csv"){let text=await file.text();text=text.replace(/^\uFEFF/,"");const first=(text.split(/\r?\n/)[0]||"");if(first.includes("\t")&&!first.includes(","))text=text.split(/\r?\n/).filter(Boolean).map(line=>line.split("\t").map(csvCell).join(",")).join("\n");return text}throw new Error("请上传 .xlsx、.txt 或 .csv 文件")}
  function csvCell(v){v=String(v==null?"":v);return /[",\r\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}
  async function xlsxToCsv(buffer){const zip=await unzip(buffer),decoder=new TextDecoder();const xml=name=>{const bytes=zip[name];if(!bytes)throw new Error("Excel 文件结构不完整："+name);return new DOMParser().parseFromString(decoder.decode(bytes),"application/xml")};let shared=[];if(zip["xl/sharedStrings.xml"])shared=Array.from(xml("xl/sharedStrings.xml").getElementsByTagName("si")).map(si=>Array.from(si.getElementsByTagName("t")).map(t=>t.textContent).join(""));const sheetName=Object.keys(zip).find(n=>/^xl\/worksheets\/sheet\d+\.xml$/.test(n));if(!sheetName)throw new Error("Excel 中没有可读取的工作表");const doc=xml(sheetName),rows=[];Array.from(doc.getElementsByTagName("row")).forEach(row=>{const values=[];Array.from(row.getElementsByTagName("c")).forEach(cell=>{const ref=cell.getAttribute("r")||"A1",letters=(ref.match(/[A-Z]+/i)||["A"])[0].toUpperCase();let col=0;for(const ch of letters)col=col*26+ch.charCodeAt(0)-64;col--;const type=cell.getAttribute("t"),v=cell.getElementsByTagName("v")[0],inline=cell.getElementsByTagName("is")[0];let value=v?v.textContent:"";if(type==="s")value=shared[Number(value)]||"";else if(type==="inlineStr"&&inline)value=Array.from(inline.getElementsByTagName("t")).map(t=>t.textContent).join("");values[col]=value});if(values.some(v=>String(v||"").trim()))rows.push(values.slice(0,2))});if(!rows.length)throw new Error("Excel 工作表为空");return rows.map(row=>[0,1].map(i=>csvCell(row[i]||"")).join(",")).join("\n")}
  async function unzip(buffer){const bytes=new Uint8Array(buffer),view=new DataView(buffer);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--){if(view.getUint32(i,true)===0x06054b50){eocd=i;break}}if(eocd<0)throw new Error("不是有效的 .xlsx 文件");const total=view.getUint16(eocd+10,true),decoder=new TextDecoder(),files={};let offset=view.getUint32(eocd+16,true);for(let i=0;i<total;i++){if(view.getUint32(offset,true)!==0x02014b50)throw new Error("Excel ZIP 目录损坏");const method=view.getUint16(offset+10,true),size=view.getUint32(offset+20,true),nameLength=view.getUint16(offset+28,true),extraLength=view.getUint16(offset+30,true),commentLength=view.getUint16(offset+32,true),localOffset=view.getUint32(offset+42,true),name=decoder.decode(bytes.slice(offset+46,offset+46+nameLength));const localName=view.getUint16(localOffset+26,true),localExtra=view.getUint16(localOffset+28,true),start=localOffset+30+localName+localExtra,chunk=bytes.slice(start,start+size);if(!name.endsWith("/")){if(method===0)files[name]=chunk;else if(method===8){if(typeof DecompressionStream==="undefined")throw new Error("当前浏览器不支持 Excel 解压，请换用新版 Chrome/Edge/Safari");files[name]=new Uint8Array(await new Response(new Blob([chunk]).stream().pipeThrough(new DecompressionStream("deflate-raw"))).arrayBuffer())}else throw new Error("Excel 使用了不支持的压缩格式")}offset+=46+nameLength+extraLength+commentLength}return files}

  restore()
})()
