const test = require("node:test")
const assert = require("node:assert/strict")
const fs = require("node:fs")
const os = require("node:os")
const path = require("node:path")
const { DatabaseSync } = require("node:sqlite")
const { openDatabase, applySqliteMigrations } = require("../src/database")

test("SQLite启动时按版本记录数据库迁移", function() {
  const database = openDatabase(":memory:")
  const migrations = database.prepare("SELECT version, name, checksum FROM schema_migrations ORDER BY version").all()
  assert.equal(migrations.length >= 1, true)
  assert.equal(migrations[0].version, "001")
  assert.equal(migrations[0].name, "001_initial.sql")
  assert.match(migrations[0].checksum, /^[a-f0-9]{64}$/)
  assert.equal(database.prepare("SELECT COUNT(*) AS count FROM users").get().count, 0)
  database.close()
})

test("已执行迁移可重复检查但禁止改写历史SQL", function() {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "shuzhi-migrations-"))
  const source = path.join(__dirname, "..", "src", "migrations", "sqlite", "001_initial.sql")
  const target = path.join(directory, "001_initial.sql")
  fs.copyFileSync(source, target)
  const database = new DatabaseSync(":memory:")
  applySqliteMigrations(database, directory)
  assert.doesNotThrow(function() { applySqliteMigrations(database, directory) })
  fs.appendFileSync(target, "\n-- 不允许修改已执行迁移\n")
  assert.throws(function() { applySqliteMigrations(database, directory) }, /已被修改/)
  database.close()
  fs.rmSync(directory, { recursive:true, force:true })
})
